-- 基础配置
require("basic")
-- 快捷键映射
require("keybindings")
-- Packer插件管理
require("plugins")
-- 自动命令
require("autocmds")

-- 主题设置
require("colorscheme")
-- 插件配置
require("plugin-config.nvim-tree")
require("plugin-config.bufferline")
require("plugin-config.lualine")
require("plugin-config.telescope")
require("plugin-config.dashboard")
require("plugin-config.project")
require("plugin-config.nvim-treesitter")
require("plugin-config.indent-blankline")
require("plugin-config.gitsigns")
require("plugin-config.comment")
require("plugin-config.todocomments")
require("plugin-config.toggleterm")
require("plugin-config.surround")
require("plugin-config.nvim-autopairs")
require("plugin-config.nvim-spectre")
require("plugin-config.auto-session")
require("plugin-config.nvim-colorizer")
require("plugin-config.fidget")
require("plugin-config.undotree")
require("plugin-config.renamer")
require("plugin-config.translate")
require("plugin-config.cursorline")
require("plugin-config.jk")
require("plugin-config.autosave")
require("plugin-config.lastplace")
-- 内置LSP (新增)
require("lsp.setup")
require("lsp.cmp")
require("lsp.ui")
-- require("lsp.formatter")
require("lsp.null-ls")
